# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  view:
    view_response_listener:  true
  #    exception:
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: ^/api, priorities: [ json, xml ], fallback_format: json, prefer_extension: true }
      - { path: ^/, priorities: [ 'text/html', '*/*' ], fallback_format: html, prefer_extension: true }
