controllers:
    resource: ../../src/Controller/
    type: annotation
rest_controllers:
    resource: ../../src/Controller/Rest
    type: annotation
    prefix: /api
kernel:
    resource: ../../src/Kernel.php
    type: annotation